input {
    sensitivity = -0.1 # -1.0 - 1.0, 0 means no modification.
}


monitor=eDP-1, highres, 0x0, auto, bitdepth, 10
monitor=DP-3, highres, auto-down, auto, bitdepth, 10

# currently adding this will completely brick hyprland sometimes, hdr eventually...
# monitorv2 {
#     output = eDP-1
#     mode = highres
#     position = 0x0
#     scale = auto
#     bitdepth = 10
#     cm = hdredid
#     supports_wide_color = 1
#     supports_hdr = 1
#     sdr_min_luminance = 0.005
#     sdr_max_luminance = 200
#     # sdr_eotf = srgb
# }

exec-once = [ monitor 1; workspace r~1 silent; ] kitty -e btop
exec-once = [ monitor 1; workspace r~2 silent; ] discord