input {
    sensitivity = -0.1 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
}

monitor=eDP-1, highres, 0x0, auto, bitdepth, 10
monitor=DP-3, highres, auto-down, auto, bitdepth, 10

# currently adding this will completely brick hyprland sometimes, hdr eventually...
# monitorv2 {
#     output = eDP-1
#     mode = highres
#     position = 0x0
#     scale = auto
#     bitdepth = 10
#     cm = hdredid
#     supports_wide_color = 1
#     supports_hdr = 1
#     sdr_min_luminance = 0.005
#     sdr_max_luminance = 200
#     # sdr_eotf = srgb
# }

windowrule = match:class steam,

bind = , code:248, exec, toggle_screenpad
bind = , XF86MonBrightnessUp, exec, brightnessctl --device intel_backlight set +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl --device intel_backlight set 5%-

# make bottom touch screen actually toucj it's screen (mochie wrote this while high, crritival CVE in my xoncinfig immimentn owo)
device {
    name = elan9009:00-04f3:2c23
    output = DP-3
}

# env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card2
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
# env = AQ_FORCE_LINEAR_BLIT,0
env = MOZ_DISABLE_RDD_SANDBOX,1

exec-once = [ monitor 1; workspace r~1 silent; ] kitty -e btop
exec-once = [ monitor 1; workspace r~2 silent; ] discord
