# https://wiki.hypr.land/Configuring/
source = ~/.config/hypr/hyprconf/*.conf

# hyprlang if IS_CASSIEBOX
source = ~/.config/hypr/cassiebox.conf
# hyprlang endif
# hyprlang if IS_CASSIETOP
source = ~/.config/hypr/cassietop.conf
# hyprlang endif

# https://wiki.hypr.land/Configuring/Master-Layout/
master {
    new_status = master
}
# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us
    follow_mouse = 1
}

# https://wiki.hypr.land/Configuring/Dispatchers/#executing-with-rules
exec-once = hyprpaper
exec-once = hyprlauncher -d
exec-once = wl-paste --watch cliphist store
exec-once = quickshell -d -n

# hacky fix for stuff just not wanting to work on boot
exec-once = sleep 5 && hyprctl reload
exec-once = sleep 10 && hyprctl reload
exec-once = sleep 15 && hyprctl reload
exec-once = sleep 30 && hyprctl reload
exec-once = sleep 60 && hyprctl reload
exec-once = sleep 120 && hyprctl reload
